version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3-node-browsers
    steps:
      - checkout
      - restore_cache: # the version on this cache changes rarely, only when a significant setting breaks the cache
          key:
            dotcache-cache-{{checksum ".circleci/config.yml" }}-{{ checksum
            "package.json" }}
      - run:
          name: Setup Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - save_cache: # special step to save the dependency cache
          key:
            dotcache-cache-{{checksum ".circleci/config.yml" }}-{{ checksum
            "package.json" }}
          paths:
            - ~/.cache
      - run: # run tests
          name: Run Test and Coverage
          command: |
            # codecoverage not working yet
            #./cc-test-reporter before-build
            yarn test
            #./cc-test-reporter after-build --exit-code $?
      - run:
          name: Build static files for serving
          command: |
            yarn build
      - run:
          name: Set up python tools for backend
          command: |
            cd server
            sudo make install-smartcard
            make install-dependencies
            make install-dev-dependencies
      - run:
          name: Run Python Tests and Coverage
          command: |
            cd server
            pipenv run make coverage
